# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.srcs/sources_1/ip/czarodziej/czarodziej.xci
# IP: The module: 'czarodziej' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.srcs/sources_1/ip/czarodziej/czarodziej.xci
# IP: The module: 'czarodziej' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/czarodziej/czarodziej_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'czarodziej'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
