# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.srcs/sources_1/ip/ILA/ILA.xci
# IP: The module: 'ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.srcs/sources_1/ip/ILA/ILA.xci
# IP: The module: 'ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jakub/Desktop/KonwerterLiczb/KonwerterLiczb.gen/sources_1/ip/ILA/ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
